
// function to suggest the location as per you entry in the location field in the user job search by location page
// it will content the list of ciity or county as the user inputs the letters
function complete() {
	  new Autocompleter.Local(
	    "city", //element where user is entering text that needs to be matched
	    "cityarea", //element to fill with matches
	    // array of all the list of county and city in Maryland
		["Aberdeen" , "Aberdeen Proving Ground" , "Accident" , "Accokeek" , "Adamstown" , 
"Adelphi" , "Algonquin" , 
"Allen" , "Andrews " , "Annapolis" , "Annapolis Neck" , "Antietam" , "Aquasco" , "Arbutus" , "Arden on the Severn" , "Arnold" , "Ashton-Sandy Spring" , "Aspen Hill" , "Baden" , "Bagtown" , "Bakersville" , "Ballenger " , "Creek" , "Baltimore" , "Baltimore Highland" , "Barclay" ,
 "Barnesville" , 
"Barrelville" , "Barton" , "Bartonsville" , "Beaver " , "Creek" , "Bel Air" , "Bel Air North" , "Bel Air South" , "Bel Air town" , "Beltsville" , "Benedict" , "Bensville" , "Berlin" , "Berwyn Heights" , "Bethesda" , "Betterton" , "Bier" ,
"Big Pool         ",
"Big Spring       ",
"Bishopville      ",
"Bivalve          ",
"Bladensburg      ",
"Bloomington      ",
"Boonsboro        ",
"Bowie            ",
"Bowleys Quarters ",
"Bowling Green    ",
"Bowmans Addition ",
"Braddock Heights ",
"Brandywine       ",
"Breathedsville   ",
"Brentwood        ",
"Brock Hall       ",
"Brookeville      ",
"Brooklyn Park    ",
"Brookmont        ",
"Brookview        ",
"Broomes Island   ",
"Brownsville      ",
"Brunswick        ",
"Bryans Road      ",
"Bryantown        ",
"Buckeystown      ",
"Burkittsville    ",
"Burtonsville     ",
"Butlertown       ",
"Cabin John       ",
"California       ",
"Calvert Beach    ",
"Calverton        ",
"Cambridge        ",
"Camp Springs     ",
"Cape St. Claire  ",
"Capitol Heights  ",
"Carlos           ",
"Carney           ",
"Catonsville      ",
"Cavetown         ",
"Cearfoss         ",
"Cecilton         ",
"Cedarville       ",
"Centreville      ",
"Chance           ",
"Charlestown      ",
"Charlotte Hall          ",
"Charlton                       ",
"Chesapeake Beach          ",
"Chesapeake City           ",
"Chesapeake Ranch Estates       ",
"Chester                        ",
"Chestertown                    ",
"Cheverly                       ",
"Chevy Chase               ",
"Chevy Chase CDP      ",
"Chevy Chase Section Five  ",
"Chevy Chase Section Three ",
"Chevy Chase View          ",
"Chevy Chase Village       ",
"Chewsville                     ",
"Chillum                        ",
"Choptank                       ",
"Church Creek              ",
"Church Hill                    ",
"Clarksburg                      ",
"Clarysville                     ",
"Clear Spring                    ",
"Clinton                         ",
"Cloverly                        ",
"Cobb Island                     ",
"Cockeysville                    ",
"Colesville                      ",
"College Park                    ",
"Colmar Manor                    ",
"Columbia                        ",
"Coral Hills                     ",
"Cordova                         ",
"Corriganville                   ",
"Cottage City               ",
"Crellin                         ",
"Cresaptown                      ",
"Crisfield                       ",
"Crofton                         ",
"Croom                           ",
"Crownsville                     ",
"Cumberland                      ",
"Damascus                             ",
"Dames Quarter                        ",
"Danville                             ",
"Dargan                               ",
"Darlington                           ",
"Darnestown                           ",
"Dawson                               ",
"Deal Island                          ",
"Deale                                ",
"Deer Park                            ",
"Delmar                               ",
"Denton                               ",
"Derwood                              ",
"Detmold                              ",
"District Heights                     ",
"Downsville                           ",
"Drum Point                           ",
"Dundalk                              ",
"Dunkirk                              ",
"Eagle Harbor                         ",
"Eakles Mill                          ",
"East New Market                      ",
"East Riverdale                       ",
"Easton                               ",
"Eckhart Mines                        ",
"Eden                                 ",
"Edesville                            ",
"Edgemere                             ",
"Edgemont                             ",
"Edgewater                            ",
"Edgewood                             ",
"Edmonston                            ",
"Eldersburg                           ",
"Eldorado                             ",
"Elkridge                             ",
"Elkton                               ",
"Ellerslie                            ",
"Ellicott City                   ",
"Elliott                              ",
"Emmitsburg                           ",
"Ernstville                           ",
"Essex                                ",
"Fairland                             ",
"Fairlee                              ",
"Fairmount                            ",
"Fairmount Heights                    ",
"Fairplay                             ",
"Fairview                             ",
"Fairwood                             ",
"Fallston                             ",
"Federalsburg                         ",
"Ferndale                             ",
"Finzel                               ",
"Fishing Creek                   ",
"Flintstone                           ",
"Forest Glen                          ",
"Forest Heights                       ",
"Forestville                          ",
"Fort Meade                           ",
"Fort Ritchie                         ",
"Fort Washington                      ",
"Fountainhead-Orchard Hills           ",
"Four Corners                    ",
"Franklin                             ",
"Frederick                            ",
"Frenchtown-Rumbly                    ",
"Friendly                             ",
"Friendship                           ",
"Friendship Heights Village           ",
"Friendsville                         ",
"Frostburg                            ",
"Fruitland                            ",
"Fulton                               ",
"Funkstown                            ",
"Gaithersburg                         ",
"Galena                               ",
"Galestown                            ",
"Galesville                           ",
"Gambrills                            ",
"Gapland                              ",
"Garrett Park                         ",
"Garretts Mill                        ",
"Garrison                             ",
"Georgetown                           ",
"Germantown                           ",
"Gilmore                              ",
"Girdletree                           ",
"Glassmanor                           ",
"Glen Burnie                     ",
"Glen Echo                            ",
"Glenarden                            ",
"Glenmont                             ",
"Glenn Dale                           ",
"Golden Beach                    ",
"Goldsboro                            ",
"Gorman                               ",
"Grahamtown                           ",
"Grantsville                          ",
"Grasonville                          ",
"Greenbelt                            ",
"Greensboro                           ",
"Greensburg                           ",
"Hagerstown                           ",
"Halfway                              ",
"Hampstead                            ",
"Hampton                              ",
"Hancock                              ",
"Havre de Grace                       ",
"Hebron                               ",
"Henderson                            ",
"Herald Harbor                        ",
"Highfield-Cascade               ",
"Highland                             ",
"Highland Beach                  ",
"Hillandale                           ",
"Hillcrest Heights                    ",
"Hillsboro                            ",
"Hughesville                          ",
"Huntingtown                          ",
"Hurlock                              ",
"Hutton                               ",
"Hyattsville                          ",
"Ilchester                            ",
"Indian Head                          ",
"Indian Springs                       ",
"Jarrettsville                        ",
"Jefferson                            ",
"Jennings                             ",
"Jessup                               ",
"Jesterville                          ",
"Joppatowne                           ",
"Jugtown                              ",
"Keedysville                          ",
"Kemp Mill                            ",
"Kemps Mill                           ",
"Kennedyville                         ",
"Kensington                           ",
"Kent Narrows                         ",
"Kettering                            ",
"Kingstown                            ",
"Kingsville                           ",
"Kitzmiller                           ",
"Klondike                             ",
"Konterra                             ",
"La Plata                             ",
"La Vale                              ",
"Lake Arbor                      ",
"Lake Shore                           ",
"Landover                             ",
"Landover Hills                       ",
"Langley Park                         ",
"Lanham                               ",
"Lansdowne                            ",
"Largo                                ",
"Laurel                               ",
"Layhill                              ",
"Laytonsville                         ",
"Leisure World                        ",
"Leitersburg                          ",
"Leonardtown                          ",
"Lexington Park                       ",
"Libertytown                          ",
"Linganore                            ",
"Linthicum                            ",
"Little Orleans                       ",
"Loch Lynn Heights                    ",
"Lochearn                             ",
"Lonaconing                           ",
"Long Beach                      ",
"Luke                                 ",
"Lusby                                ",
"Lutherville                          ",
"Madison                              ",
"Manchester                           ",
"Mapleville                           ",
"Mardela Springs                      ",
"Marlboro Meadows                     ",
"Marlboro Village                     ",
"Marlow Heights                       ",
"Marlton                              ",
"Martin's Additions              ",
"Marydel                              ",
"Maryland City                   ",
"Maugansville                         ",
"Mayo                                 ",
"Mays Chapel                     ",
"Mc Coole                         ",
"Mechanicsville                       ",
"Melwood                              ",
"Mercersville                         ",
"Middle River                         ",
"Middleburg                           ",
"Middletown                           ",
"Midland                              ",
"Midlothian                           ",
"Milford Mill                         ",
"Millington                           ",
"Mitchellville                        ",
"Monrovia                             ",
"Montgomery Village                   ",
"Morningside                          ",
"Moscow                               ",
"Mount Aetna                     ",
"Mount Airy                      ",
"Mount Briar                     ",
"Mount Lena                           ",
"Mount Rainier                        ",
"Mount Savage                         ",
"Mount Vernon                         ",
"Mountain Lake Park                   ",
"Myersville                           ",
"Nanticoke                            ",
"Nanticoke Acres                 ",
"National                             ",
"National Harbor                      ",
"Naval Academy                   ",
"New Carrollton                  ",
"New Market                           ",
"New Windsor                          ",
"Newark                               ",
"Nikep                                ",
"North Beach                     ",
"North Bethesda                  ",
"North Brentwood                 ",
"North Chevy " , "Chase          ",
"North East                           ",
"North Kensington                     ",
"North Laurel                         ",
"North Potomac                        ",
"Oakland                              ",
"Ocean                                ",
"Ocean City                      ",
"Ocean Pines                          ",
"Odenton                              ",
"Oldtown                              ",
"Olney                                ",
"Overlea                              ",
"Owings                               ",
"Owings Mills                         ",
"Oxford                               ",
"Oxon Hill                            ",
"Paramount-Long Meadow                ",
"Parkville                            ",
"Parole                               ",
"Parsonsburg                          ",
"Pasadena                             ",
"Pecktonville                         ",
"Peppermill Village                   ",
"Perry Hall                           ",
"Perryman                             ",
"Perryville                           ",
"Pikesville                           ",
"Pinesburg                            ",
"Piney Point                          ",
"Pittsville                           ",
"Pleasant Grove                       ",
"Pleasant Hills                       ",
"Pocomoke City                   ",
"Point of Rocks                       ",
"Pomfret                              ",
"Pondsville                           ",
"Poolesville                          ",
"Port Deposit                         ",
"Port Tobacco Village                 ",
"Potomac                              ",
"Potomac Heights                      ",
"Potomac Park                         ",
"Powellville                          ",
"Preston                              ",
"Prince Frederick                     ",
"Princess Anne                   ",
"Pylesville                           ",
"Quantico                             ",
"Queen Anne                      ",
"Queen Anne town                 ",
"Queenstown                           ",
"Randallstown                         ",
"Rawlings                             ",
"Redland                              ",
"Reid                                 ",
"Reisterstown                         ",
"Ridgely                              ",
"Ringgold                             ",
"Rising Sun                           ",
"Riva                                 ",
"Riverdale Park                       ",
"Riverside                            ",
"Riviera Beach                   ",
"Robinwood                            ",
"Rock Hall                            ",
"Rock Point                           ",
"Rockville                            ",
"Rohrersville                         ",
"Rosaryville                          ",
"Rosedale                             ",
"Rosemont                             ",
"Rossville                            ",
"Sabillasville                        ",
"Salisbury                            ",
"San Mar                              ",
"Sandy Hook                           ",
"Savage                               ",
"Scaggsville                          ",
"Seabrook                             ",
"Seat Pleasant                        ",
"Secretary                            ",
"Severn                               ",
"Severna Park                         ",
"Shady Side                           ",
"Shaft                                ",
"Sharpsburg                           ",
"Sharptown                            ",
"Silver Hill                          ",
"Silver Spring                        ",
"Smith Island                         ",
"Smithsburg                           ",
"Snow Hill                            ",
"Solomons                             ",
"Somerset                             ",
"South Kensington                     ",
"South Laurel                         ",
"Spencerville                         ",
"Spring Gap                           ",
"Spring Ridge                         ",
"Springdale                           ",
"St. George Island                    ",
"St. James                            ",
"St. Leonard                          ",
"St. Michaels                         ",
"Stevensville                         ",
"Stockton                             ",
"Sudlersville                         ",
"Suitland                             ",
"Summerfield                          ",
"Swanton                              ",
"Sykesville                           ",
"Takoma Park                          ",
"Tall Timbers                         ",
"Taneytown                            ",
"Taylors Island                       ",
"Temple Hills                         ",
"Templeville                          ",
"Thurmont                             ",
"Tilghman Island                      ",
"Tilghmanton                          ",
"Timonium                             ",
"Tolchester                           ",
"Towson                               ",
"Trappe                               ",
"Travilah                             ",
"Trego-Rohrersville Station           ",
"Tyaskin                              ",
"Union Bridge                    ",
"University Park                      ",
"Upper Marlboro                       ",
"Urbana                               ",
"Vale Summit                          ",
"Vienna                               ",
"Waldorf                              ",
"Walker Mill                          ",
"Walkersville                         ",
"Washington Grove                     ",
"Waterview                            ",
"West Denton                          ",
"West Laurel                          ",
"West Ocean City                 ",
"West Pocomoke                        ",
"Westernport                          ",
"Westminster                          ",
"Westphalia                           ",
"Whaleyville                          ",
"Wheaton                              ",
"White Marsh                          ",
"White Oak                            ",
"Whitehaven                           ",
"Willards                             ",
"Williamsport                         ",
"Williston                            ",
"Wilson-Conococheague            ",
"Woodland                             ",
"Woodlawn                             ",
"Woodlawn CDP (Prince George's County)",
"Woodmore",
"Woodsboro                               ",
"Worton                                  ",
"Yarrowsburg                             ",
"Zihlman                                 "
		], //array of matches
	    {}
	  );
};